// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "Playa",
    platforms: [.macOS(.v14), .tvOS(.v17)],
    products: [
        // Used by the Apple TV app, which is built from the Xcode project generated by project.yml.
        .library(name: "PlayaCore", targets: ["PlayaCore"]),
    ],
    dependencies: [
        // Prebuilt, self-contained libmpv (LGPL build) for macOS, iOS and tvOS.
        .package(url: "https://github.com/mpvkit/MPVKit.git", exact: "0.41.0"),
    ],
    targets: [
        .target(name: "PlayaCore"),
        .executableTarget(
            name: "Playa",
            dependencies: [
                "PlayaCore",
                .product(name: "MPVKit", package: "MPVKit"),
            ]
        ),
        .testTarget(
            name: "PlayaCoreTests",
            dependencies: ["PlayaCore"]
        ),
    ]
)
